CREATE TABLE MQR_USER (MQR_USER_ID BIGINT NOT NULL, EMAIL VARCHAR(255) NOT NULL, FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, NICKNAME VARCHAR(255) NOT NULL, PASSWORD VARCHAR(1024) NOT NULL, MQR_USER_SESSION_ID BIGINT, PRIMARY KEY (MQR_USER_ID));
CREATE TABLE MQR_USER_ROLE (MQR_USER_ROLE_ID BIGINT NOT NULL, ROLE VARCHAR(256) NOT NULL, MQR_USER_ID BIGINT NOT NULL, PRIMARY KEY (MQR_USER_ROLE_ID));
CREATE TABLE MQR_CATALOG (MQR_CATALOG_ID BIGINT NOT NULL, DESCRIPTION VARCHAR(4096) NOT NULL, NAME VARCHAR(4096) NOT NULL, XSD BYTEA NOT NULL, MQR_USER_ID BIGINT NOT NULL, PRIMARY KEY (MQR_CATALOG_ID));
CREATE TABLE MQR_CATALOG_STAT (MQR_CATALOG_STAT_ID BIGINT NOT NULL, NUMBER_OF_REFERENCES BIGINT NOT NULL, STARS FLOAT NOT NULL, MQR_CATALOG_ID BIGINT NOT NULL, PRIMARY KEY (MQR_CATALOG_STAT_ID));
CREATE TABLE MQR_REPOSITORY (MQR_REPOSITORY_ID BIGINT NOT NULL, CORRELATION_ID VARCHAR(4096), PERSONAL BOOLEAN, XML BYTEA NOT NULL, MQR_USER_ID BIGINT NOT NULL, PRIMARY KEY (MQR_REPOSITORY_ID));
CREATE TABLE MQR_LINK (MQR_LINK_ID BIGINT NOT NULL, OTHER_CODE VARCHAR(4096) NOT NULL, MQR_REPOSITORY_ID BIGINT NOT NULL, MQR_USER_ID BIGINT NOT NULL, PRIMARY KEY (MQR_LINK_ID));
CREATE TABLE MQR_CATALOG_CATALOG (MQR_CATALOG_REFERRING_ID BIGINT NOT NULL, MQR_CATALOG_REFERRED_ID BIGINT NOT NULL, PRIMARY KEY (MQR_CATALOG_REFERRING_ID, MQR_CATALOG_REFERRED_ID));
CREATE TABLE MQR_REPOSITORY_CATALOG (MQR_CATALOG_ID BIGINT NOT NULL, MQR_REPOSITORY_ID BIGINT NOT NULL, PRIMARY KEY (MQR_CATALOG_ID, MQR_REPOSITORY_ID));

CREATE UNIQUE INDEX MQR_USER_I1 ON MQR_USER (EMAIL);
CREATE UNIQUE INDEX MQR_USER_I2 ON MQR_USER (NICKNAME);
CREATE INDEX MQR_USER_ROLE_I1 ON MQR_USER_ROLE (MQR_USER_ID);
CREATE INDEX MQR_CATALOG_I1 ON MQR_CATALOG (MQR_USER_ID);
CREATE INDEX MQR_CATALOG_I2 ON MQR_CATALOG (NAME);
CREATE INDEX MQR_CATALOG_I3 ON MQR_CATALOG (DESCRIPTION);
CREATE UNIQUE INDEX MQR_CATALOG_STAT_I1 ON MQR_CATALOG_STAT (MQR_CATALOG_ID);
CREATE INDEX MQR_REPOSITORY_I1 ON MQR_REPOSITORY (CORRELATION_ID);
CREATE UNIQUE INDEX MQR_LINK_I1 ON MQR_LINK (OTHER_CODE);
CREATE INDEX MQR_LINK_I2 ON MQR_LINK (MQR_REPOSITORY_ID);

ALTER TABLE MQR_USER ADD CONSTRAINT FK_MQR_USER_MQR_USER_SESSION_ID FOREIGN KEY (MQR_USER_SESSION_ID) REFERENCES MQR_USER_SESSION (MQR_USER_SESSION_ID);
ALTER TABLE MQR_USER_ROLE ADD CONSTRAINT FK_MQR_USER_ROLE_MQR_USER_ID FOREIGN KEY (MQR_USER_ID) REFERENCES MQR_USER (MQR_USER_ID);
ALTER TABLE MQR_CATALOG ADD CONSTRAINT FK_MQR_CATALOG_MQR_USER_ID FOREIGN KEY (MQR_USER_ID) REFERENCES MQR_USER (MQR_USER_ID);
ALTER TABLE MQR_CATALOG_STAT ADD CONSTRAINT FK_MQR_CATALOG_STAT_MQR_CATALOG_ID FOREIGN KEY (MQR_CATALOG_ID) REFERENCES MQR_CATALOG (MQR_CATALOG_ID);
ALTER TABLE MQR_REPOSITORY ADD CONSTRAINT FK_MQR_REPOSITORY_MQR_USER_ID FOREIGN KEY (MQR_USER_ID) REFERENCES MQR_USER (MQR_USER_ID);
ALTER TABLE MQR_LINK ADD CONSTRAINT FK_MQR_LINK_MQR_REPOSITORY_ID FOREIGN KEY (MQR_REPOSITORY_ID) REFERENCES MQR_REPOSITORY (MQR_REPOSITORY_ID);
ALTER TABLE MQR_LINK ADD CONSTRAINT FK_MQR_LINK_MQR_USER_ID FOREIGN KEY (MQR_USER_ID) REFERENCES MQR_USER (MQR_USER_ID);
ALTER TABLE MQR_CATALOG_CATALOG ADD CONSTRAINT FK_MQR_CATALOG_CATALOG_MQR_CATALOG_REFERRING_ID FOREIGN KEY (MQR_CATALOG_REFERRING_ID) REFERENCES MQR_CATALOG (MQR_CATALOG_ID);
ALTER TABLE MQR_CATALOG_CATALOG ADD CONSTRAINT FK_MQR_CATALOG_CATALOG_MQR_CATALOG_REFERRED_ID FOREIGN KEY (MQR_CATALOG_REFERRED_ID) REFERENCES MQR_CATALOG (MQR_CATALOG_ID);
ALTER TABLE MQR_REPOSITORY_CATALOG ADD CONSTRAINT FK_MQR_REPOSITORY_CATALOG_MQR_CATALOG_ID FOREIGN KEY (MQR_CATALOG_ID) REFERENCES MQR_CATALOG (MQR_CATALOG_ID);
ALTER TABLE MQR_REPOSITORY_CATALOG ADD CONSTRAINT FK_MQR_REPOSITORY_CATALOG_MQR_REPOSITORY_ID FOREIGN KEY (MQR_REPOSITORY_ID) REFERENCES MQR_REPOSITORY (MQR_REPOSITORY_ID);

CREATE SEQUENCE MQR_USER_ID_SEQ START WITH 1;
CREATE SEQUENCE MQR_USER_ROLE_ID_SEQ START WITH 1;
CREATE SEQUENCE MQR_CATALOG_ID_SEQ START WITH 1;
CREATE SEQUENCE MQR_CATALOG_STAT_ID_SEQ START WITH 1;
CREATE SEQUENCE MQR_REPOSITORY_ID_SEQ START WITH 1;
CREATE SEQUENCE MQR_LINK_ID_SEQ START WITH 1;
